name: itm
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - nvidia::cuda=12.1
  - pip
  - pip:
    - umap-learn==0.5.3
    - hdbscan==0.8.33
    - dill==0.3.7
    - numpy==1.24.2
    - scipy==1.11.3
    - scikit-learn==1.2.2
    - numba==0.58.1
    - pynndescent==0.5.11
    - "pandas<2.0.0"
    - bertopic
    - transformers==4.32
    - accelerate==0.22.0
    - bitsandbytes==0.41.1
    - sentencepiece
    - sentence-transformers==2.2.2
    - roboflow
    - supervision
    - pycocotools
    - addict
    - yapf
    - timm
    - ftfy
    - regex
    - einops
    - fvcore
    - eva-decord
    - iopath
    - matplotlib
    - types-regex
    - mayavi
    - cartopy
    - fschat
    - protobuf
    - pytorchvideo

